#!/usr/bin/env python3
"""Generate images with OpenAI gpt-image-2 or Google Gemini and preview them in the terminal.

Usage:
    generate_image.py "<prompt>" [--provider openai|gemini] [--race]
                      [--tier low|medium|high] [--aspect 1:1] [--size WxH]
                      [-n N] [--thinking low|medium|high]
                      [--out-dir PATH] [--no-display]

Providers:
    openai  (default) -> gpt-image-2, reads OPENAI_API_KEY
    gemini            -> Gemini native image gen (Nano Banana), reads GEMINI_API_KEY
    --race            -> generate from BOTH providers for a side-by-side compare.

The --tier knob picks an equivalent-caliber model/quality on each provider so a
--race stays apples-to-apples. Saves PNGs to ~/Pictures/ai-generated by default
and opens each in the system image viewer (macOS `open`); other platforms just
print the saved path.
"""

import argparse
import base64
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

OPENAI_URL = "https://api.openai.com/v1/images/generations"
GEMINI_HOST = "https://generativelanguage.googleapis.com"
DEFAULT_OUT_DIR = Path.home() / "Pictures" / "ai-generated"

# One --tier knob maps to a comparable model/quality on each provider, so a
# --race compares like with like. OpenAI's gpt-image-2 is a single model whose
# tier is its `quality` setting; Gemini swaps the actual model. Resolution is a
# separate axis (--resolution), not baked into the tier.
TIERS = {
    "low":    {"quality": "low",    "gemini_model": "gemini-2.5-flash-image"},
    "medium": {"quality": "medium", "gemini_model": "gemini-3.1-flash-image"},
    "high":   {"quality": "high",   "gemini_model": "gemini-3-pro-image"},
}

# Output detail. Default moderate; raise only on request. Use a real API
# parameter where one exists, otherwise fold the request into the prompt text.
RESOLUTIONS = ["1K", "2K", "4K"]
DEFAULT_RESOLUTION = "1K"

# A single --aspect knob drives both providers. OpenAI takes fixed pixel sizes,
# Gemini takes ratio strings, so each aspect maps to the nearest supported option.
ASPECTS = {
    "1:1":  {"openai": "1024x1024", "gemini": "1:1"},
    "3:2":  {"openai": "1536x1024", "gemini": "3:2"},
    "2:3":  {"openai": "1024x1536", "gemini": "2:3"},
    "4:3":  {"openai": "1536x1024", "gemini": "4:3"},
    "3:4":  {"openai": "1024x1536", "gemini": "3:4"},
    "16:9": {"openai": "2000x1000", "gemini": "16:9"},
    "9:16": {"openai": "1000x2000", "gemini": "9:16"},
}


def curl_json(url: str, headers: list[str], payload: dict) -> dict:
    """POST JSON via curl and return the parsed response.

    curl (not urllib) sidesteps Python SSL cert headaches — Homebrew/pyenv
    Python often lacks certifi bundles, and curl uses the system keychain.
    """
    cmd = ["curl", "-sS", "--fail-with-body", "-X", "POST", url]
    for h in headers:
        cmd += ["-H", h]
    cmd += ["-H", "Content-Type: application/json",
            "-d", json.dumps(payload), "--max-time", "600"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"API request failed (curl exit {result.returncode}):\n"
                 f"{result.stdout or result.stderr}")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        sys.exit(f"Unexpected response:\n{result.stdout[:2000]}")


def call_openai(prompt: str, size: str, n: int, quality: str,
                thinking: str | None) -> list[bytes]:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        sys.exit("ERROR: OPENAI_API_KEY is not set. Export it and try again.")

    payload: dict = {
        "model": "gpt-image-2",
        "prompt": prompt,
        "size": size,
        "n": n,
        "quality": quality,
    }
    if thinking:
        payload["thinking"] = thinking

    print(f"[openai] requesting {n} image(s) from gpt-image-2 ({size}, "
          f"quality={quality}" + (f", thinking={thinking}" if thinking else "")
          + ")...", file=sys.stderr)

    data = curl_json(OPENAI_URL, [f"Authorization: Bearer {api_key}"], payload)
    if "error" in data:
        sys.exit(f"OpenAI API error: {data['error']}")
    if "data" not in data:
        sys.exit(f"Unexpected response:\n{json.dumps(data)[:2000]}")
    return [base64.b64decode(item["b64_json"]) for item in data["data"]]


def call_gemini(prompt: str, model: str, aspect: str, image_size: str,
                n: int) -> list[bytes]:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        sys.exit("ERROR: GEMINI_API_KEY is not set. Export it and try again.")

    ratio = ASPECTS[aspect]["gemini"]
    url = f"{GEMINI_HOST}/v1/models/{model}:generateContent"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseModalities": ["TEXT", "IMAGE"],
            "responseFormat": {"image": {"aspectRatio": ratio,
                                         "imageSize": image_size}},
        },
    }
    print(f"[gemini] requesting {n} image(s) from {model} "
          f"({ratio}, {image_size})...", file=sys.stderr)

    # Gemini native image gen returns one image per call, so loop for n>1.
    images: list[bytes] = []
    for _ in range(n):
        data = curl_json(url, [f"x-goog-api-key: {api_key}"], payload)
        if "error" in data:
            sys.exit(f"Gemini API error: {data['error']}")
        images += _extract_inline_images(data)
    if not images:
        sys.exit("Gemini returned no image data — try a different prompt or tier.")
    return images


def resolve_resolution(prompt: str, provider: str, resolution: str) -> tuple[str, str]:
    """Apply the requested output resolution per provider.

    Returns the (possibly augmented) prompt and the Gemini imageSize value.
    Gemini native image gen takes imageSize as a real parameter (1K/2K/4K).
    OpenAI gpt-image-2 has no resolution parameter — pixel count is fixed by
    --size — so an explicit above-default request is folded into the prompt
    text instead, where it still nudges detail.
    """
    if provider == "gemini":
        return prompt, resolution
    if resolution != DEFAULT_RESOLUTION:
        prompt = f"{prompt} (ultra-high resolution, {resolution}, highly detailed)"
    return prompt, resolution


def _extract_inline_images(data: dict) -> list[bytes]:
    """Pull base64 image bytes out of a generateContent response.

    REST responses have varied between camelCase (inlineData/mimeType) and
    snake_case (inline_data) across versions, so accept either.
    """
    out: list[bytes] = []
    for cand in data.get("candidates", []):
        for part in cand.get("content", {}).get("parts", []):
            blob = part.get("inlineData") or part.get("inline_data")
            if blob and blob.get("data"):
                out.append(base64.b64decode(blob["data"]))
    return out


def display(path: Path) -> None:
    """Open the saved image in the system viewer. macOS only; elsewhere the
    printed path is the result."""
    if sys.platform == "darwin":
        subprocess.run(["open", str(path)], check=False)


def save_images(images: list[bytes], out_dir: Path, stamp: str,
                label: str | None) -> list[Path]:
    """Save bytes to PNGs, tagging filenames with the provider label when set."""
    tag = f"-{label}" if label else ""
    paths: list[Path] = []
    for i, data in enumerate(images):
        suffix = f"-{i + 1}" if len(images) > 1 else ""
        path = out_dir / f"{stamp}{tag}{suffix}.png"
        path.write_bytes(data)
        paths.append(path)
        print(str(path))
    return paths


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate images with OpenAI gpt-image-2 or Google Gemini.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("prompt", help="Image prompt (natural language).")
    ap.add_argument("--provider", choices=["openai", "gemini"], default="openai",
                    help="Image backend (default: openai).")
    ap.add_argument("--race", action="store_true",
                    help="Generate from BOTH providers for a side-by-side compare.")
    ap.add_argument("--tier", choices=list(TIERS), default="high",
                    help="Quality/model tier, applied per provider (default: high).")
    ap.add_argument("--aspect", choices=list(ASPECTS), default="1:1",
                    help="Cross-provider aspect ratio (default: 1:1).")
    ap.add_argument("--resolution", choices=RESOLUTIONS, default=DEFAULT_RESOLUTION,
                    help=f"Output detail level (default: {DEFAULT_RESOLUTION}, "
                         "moderate). Gemini uses its imageSize param; OpenAI has "
                         "none, so higher values pass through as a prompt hint.")
    ap.add_argument("--size", default=None,
                    help="OpenAI-only pixel size override, e.g. 1536x1024 "
                         "(default: derived from --aspect).")
    ap.add_argument("-n", "--count", type=int, default=1,
                    help="Images per provider, 1-10 (default: 1).")
    ap.add_argument("--thinking", choices=["low", "medium", "high"],
                    help="OpenAI reasoning mode for complex layouts / rendered text.")
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR),
                    help=f"Output directory (default: {DEFAULT_OUT_DIR}).")
    ap.add_argument("--no-display", action="store_true",
                    help="Skip opening the system viewer.")
    args = ap.parse_args()

    if not (1 <= args.count <= 10):
        sys.exit("ERROR: -n/--count must be between 1 and 10.")

    out_dir = Path(args.out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    tier = TIERS[args.tier]
    openai_size = args.size or ASPECTS[args.aspect]["openai"]

    providers = ["openai", "gemini"] if args.race else [args.provider]
    # Tag filenames by provider whenever more than one source is in play.
    tagged = len(providers) > 1

    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    all_paths: list[tuple[str, list[Path]]] = []
    for prov in providers:
        if prov == "openai":
            prompt, _ = resolve_resolution(args.prompt, "openai", args.resolution)
            images = call_openai(prompt, openai_size, args.count,
                                 tier["quality"], args.thinking)
            label = "openai" if tagged else None
        else:
            prompt, image_size = resolve_resolution(args.prompt, "gemini", args.resolution)
            images = call_gemini(prompt, tier["gemini_model"], args.aspect,
                                 image_size, args.count)
            label = "gemini" if tagged else None
        all_paths.append((prov, save_images(images, out_dir, stamp, label)))

    if not args.no_display:
        for prov, paths in all_paths:
            if tagged:
                print(f"\n=== {prov} ===", file=sys.stderr)
            for path in paths:
                display(path)


if __name__ == "__main__":
    main()
